"""added url

Revision ID: 243ff5b810bd
Revises: 582a6b2b15f1
Create Date: 2022-03-26 20:54:24.837296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "243ff5b810bd"
down_revision = "582a6b2b15f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
