"""init

Revision ID: 582a6b2b15f1
Revises: 
Create Date: 2022-03-25 18:15:42.881318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "582a6b2b15f1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
