"""added url1

Revision ID: 78a035dd61d1
Revises: 243ff5b810bd
Create Date: 2022-03-26 20:57:14.659028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78a035dd61d1"
down_revision = "243ff5b810bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
