"""added url2

Revision ID: 82c46c1fb093
Revises: 78a035dd61d1
Create Date: 2022-03-26 20:58:44.170910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82c46c1fb093"
down_revision = "78a035dd61d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_geo_location_city", table_name="geo_location")
    op.drop_index("ix_geo_location_continent_code", table_name="geo_location")
    op.drop_index("ix_geo_location_continent_name", table_name="geo_location")
    op.drop_index("ix_geo_location_country_code", table_name="geo_location")
    op.drop_index("ix_geo_location_country_name", table_name="geo_location")
    op.drop_index("ix_geo_location_ip", table_name="geo_location")
    op.drop_index("ix_geo_location_region_code", table_name="geo_location")
    op.drop_index("ix_geo_location_region_name", table_name="geo_location")
    op.drop_index("ix_geo_location_type", table_name="geo_location")
    op.drop_index("ix_geo_location_zip", table_name="geo_location")
    op.drop_table("geo_location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_location",
        sa.Column("ip", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("continent_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("continent_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("country_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("country_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("region_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("region_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("zip", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("ip", name="geo_location_pkey"),
    )
    op.create_index("ix_geo_location_zip", "geo_location", ["zip"], unique=False)
    op.create_index("ix_geo_location_type", "geo_location", ["type"], unique=False)
    op.create_index(
        "ix_geo_location_region_name", "geo_location", ["region_name"], unique=False
    )
    op.create_index(
        "ix_geo_location_region_code", "geo_location", ["region_code"], unique=False
    )
    op.create_index("ix_geo_location_ip", "geo_location", ["ip"], unique=False)
    op.create_index(
        "ix_geo_location_country_name", "geo_location", ["country_name"], unique=False
    )
    op.create_index(
        "ix_geo_location_country_code", "geo_location", ["country_code"], unique=False
    )
    op.create_index(
        "ix_geo_location_continent_name",
        "geo_location",
        ["continent_name"],
        unique=False,
    )
    op.create_index(
        "ix_geo_location_continent_code",
        "geo_location",
        ["continent_code"],
        unique=False,
    )
    op.create_index("ix_geo_location_city", "geo_location", ["city"], unique=False)
    # ### end Alembic commands ###
